### ISSUE TITLE
Is this can work with  Digraph?

### ISSUE THREAD

**Issue by wenzezhang** [saibalmars/GraphRicciCurvature#1]
Hello, here is my problem ,when I want to work with Digraph , I got  some error message. So I want to know  if it can work with Digraph. thanks for you browsing! （^_^）

**Comment by saibalmars** [comment]
Hi, in theory it works with Digraph, but mostly right now we use that for undirected graph only so I didn't implement it :p.
For directed graph, you need to do some modification change in optimal transportation part. Basically for an edge A->B. instead of consider A and B's neighborhood, you need to consider A's in-neighborhood and B's out-neighborhood. I will find sometime these two days to add that part. Thanks for asking!

**Comment by wenzezhang** [comment]
ok , thank you !

**Comment by saibalmars** [comment]
The newly updated version support directed graph now, please have a look :)

**Comment by ArnaudFickinger** [comment]
@saibalmars Could you please elaborate on why you have chosen A's in-neighborhood and B's out-neighborhood instead of A's out-neighborhood and B's in-neighborhood?

**Comment by saibalmars** [comment]
Hi @ArnaudFickinger, 

In short, this is because we need to make sure the neighborhood nodes of A (say X) can transport it's mass to B's neighborhood nodes (say Y), so we can measure the curvature via the ratio of mass transport through X->A->B->Y or X->Z->Y. If there are more mass transport through X->A->B->Y, then it's negative curvature, if transport through X->Z->Y more, it's positive curvature.

If we pick A's out-neighborhood as X and B's in-neighborhood as Y instead, there is no guarantee that X is connected to Y.

Let me know if there is anything not clear, I can try to explain more. :)
